# Generated by Django 4.0 on 2022-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsec',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Admin Profile'),
        ),
    ]
