# Generated by Django 4.0 on 2022-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0003_adminsec_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsec',
            name='pic',
            field=models.FileField(default='avtar.jpg', upload_to='Admin Profile'),
        ),
    ]
