# Generated by Django 4.0 on 2022-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pic',
            field=models.FileField(upload_to='gallery'),
        ),
    ]
