# Generated by Django 4.0 on 2022-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0009_gallery_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
