# Generated by Django 4.0 on 2022-02-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secratory', '0005_member_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rec_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secratory.member')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secratory.adminsec')),
            ],
        ),
    ]
