# Generated by Django 4.0 on 2022-03-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0008_maintenance'),
        ('member', '0002_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='solve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secratory.adminsec'),
        ),
    ]
