# Generated by Django 4.0 on 2022-03-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secratory', '0010_delete_maintenance'),
        ('member', '0003_alter_complain_solve_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('month', models.DateField()),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('pay_id', models.CharField(max_length=50)),
                ('verify', models.BooleanField(default=False)),
                ('pay_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secratory.member')),
            ],
        ),
    ]
