# Generated by Django 4.0 on 2022-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_reqevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqevent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
