# Generated by Django 4.0 on 2022-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_reqevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqevent',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
